.PHONY: run


# Load a directory into the prompts database
load:
	go run cmd/load/main.go -db ../data/prompts.sqlite -config ../config/config.yml

load_win:
	go run cmd/load/main.go -db ../data/prompts.sqlite -dir /mnt/d/AI/Outputs/ComfyUIWin